# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]
        
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install coverage black ruff mypy
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with balck and ruff and mypy
      run: |
        # stop the build if there are Python syntax errors or undefined names
        black typejudge.py
        ruff check typejudge.py --select=ALL --ignore=D203,D212 --fix
        mypy typejudge.py
    - name: Test with coverage
      run: |
        coverage run -m unittest
        coverage report --omit=tests/*
